# This file was generated, do not modify it. # hide
F2 = [
  x^6 + 2*x^3*y^2 + y^4,
  x^3 - x^2*y^3 - x*y^4 + y^2,
  x^2 + x*y
]
# the ideals generated by F and F2 coincide
groebner(F) == groebner(F2)